### PR TITLE
updated main.css

### PR DESCRIPTION
**Pull request by mithu2649**
replaced unnecessary selectors with generalised selector

### CODE REVIEW

**Comment by mithu2649** [comment]
Please do confirm that it works. I haven't checked locally.

**Comment by codewithpandey** [comment]
Yup! I copied the code and tried it locally. Having some problems.

**Comment by mithu2649** [comment]
I guess all those selectors can be replaced with just an '*' 

and remove the box-sizing if it causes any issue

**Review by codewithpandey — APPROVED** [review]
box-sizing property is conflicting with the old CSS. Just removing that and approving the rest.

**Pull request merged**
